<?php
// script generated by Grok
// script animation type showing interaction between and server for the first 10 characters of the key
// full script here https://github.com/djalilayed/tryhackme/blob/main/Crypto%20Failures/find_key.php
// script for tryhackme room Crypto Failures Implementing your own military-grade encryption is usually not the best idea.
// room link: https://tryhackme.com/room/cryptofailures
// Target server details
$host = "10.10.76.4";
$port = 80;

// Characters to brute-force
$characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_+-=[]{}|;:,.<>?';

// ANSI color codes
define('COLOR_RESET', "\033[0m");
define('COLOR_GREEN', "\033[32m");
define('COLOR_YELLOW', "\033[33m");
define('COLOR_CYAN', "\033[36m");
define('COLOR_WHITE', "\033[37m");
define('COLOR_RED', "\033[31m");

// Function to send raw HTTP request and get cookie
function send_probe($user_agent) {
    global $host, $port;
    echo COLOR_CYAN . ">>> Sending probe: '$user_agent'" . COLOR_RESET . "\n";
    sleep(1); // Dramatic pause
    
    $fp = fsockopen($host, $port, $errno, $errstr, 30);
    if (!$fp) {
        echo COLOR_RED . "Vault resists: $errno - $errstr" . COLOR_RESET . "\n";
        return null;
    }
    
    $request = "GET / HTTP/1.1\r\n";
    $request .= "Host: $host\r\n";
    $request .= "User-Agent: $user_agent\r\n";
    $request .= "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\n";
    $request .= "Connection: close\r\n";
    $request .= "\r\n";
    
    fwrite($fp, $request);
    $response = '';
    while (!feof($fp)) {
        $response .= fgets($fp, 1024);
    }
    fclose($fp);
    
    preg_match('/Set-Cookie: secure_cookie=([^;]+)/', $response, $matches);
    $cookie = isset($matches[1]) ? $matches[1] : null;
    echo COLOR_WHITE . ">>> Server response: $cookie" . COLOR_RESET . "\n";
    sleep(1);
    return $cookie;
}

// Function to split cookie into 13-char hashes and display
function analyze_clue($cookie) {
    if (!$cookie) return null;
    $secure_cookie = urldecode($cookie);
    $hashes = [];
    $pos = 0;
    while ($pos + 13 <= strlen($secure_cookie)) {
        $hashes[] = substr($secure_cookie, $pos, 13);
        $pos += 13;
    }
    if ($pos < strlen($secure_cookie)) { // Fixed typo: $secure_crypto -> $secure_cookie
        $hashes[] = substr($secure_cookie, $pos);
    }
    echo COLOR_WHITE . ">>> Clue segments received: " . implode(", ", $hashes) . COLOR_RESET . "\n";
    sleep(1);
    return $hashes;
}

// Function to display string as 8-byte blocks
function display_blocks($string, $block_index) {
    $blocks = str_split($string, 8);
    echo COLOR_YELLOW . ">>> Server encrypts string into 8-byte blocks:" . COLOR_RESET . "\n";
    foreach ($blocks as $i => $block) {
        $highlight = ($i === $block_index) ? COLOR_GREEN : COLOR_WHITE;
        $padding = str_repeat(" ", 8 - strlen($block)); // Pad incomplete blocks
        echo "$highlight| $block$padding |" . COLOR_RESET . " ";
        sleep(0.5); // Animate block-by-block
    }
    echo "\n";
    sleep(1);
}

// Main game logic
echo COLOR_YELLOW . "=== Welcome to Crypto Cracker Lab ===" . COLOR_RESET . "\n";
echo "Initializing decryption simulator...\n";
sleep(2);
echo "Target vault: $host\n";
sleep(1);
echo "Objective: Learn how to crack the vault's secret in 10 steps!\n\n";

$known_key = "";
$position = 0;
$username = "guest:";
$separator = ":";
$max_steps = 10;

while ($position < $max_steps) {
    echo COLOR_YELLOW . "=== Step " . ($position + 1) . " ===" . COLOR_RESET . "\n";
    
    // Calculate padding
    $length = strlen($username . $separator . $known_key);
    $ua_padding_length = ((7 - $length) % 8 + 8) % 8; // Ensured 0-7
    $user_agent = str_repeat("A", $ua_padding_length);
    $prefix = $username . $user_agent . $separator . $known_key;
    
    // Send probe and get clue
    $cookie = send_probe($user_agent);
    if (!$cookie) {
        echo COLOR_RED . "Vault defenses too strong. Simulation aborted." . COLOR_RESET . "\n";
        break;
    }
    
    // Analyze clue
    $hashes = analyze_clue($cookie);
    if (!$hashes) {
        echo COLOR_RED . "Clue corrupted. Simulation aborted." . COLOR_RESET . "\n";
        break;
    }
    
    // Target lock
    $block_index = floor(strlen($prefix) / 8);
    if (!isset($hashes[$block_index])) {
        echo COLOR_YELLOW . "Vault simulation complete! Secret so far: $known_key" . COLOR_RESET . "\n";
        break;
    }
    
    $target_block = $hashes[$block_index];
    $salt = substr($target_block, 0, 2);
    echo COLOR_WHITE . ">>> Targeting lock $block_index, hash: $target_block" . COLOR_RESET . "\n";
    echo COLOR_WHITE . ">>> Salt used: $salt" . COLOR_RESET . "\n";
    
    // Display blocks being encrypted
    display_blocks($prefix, $block_index);
    
    // Crack the lock
    $found = false;
    foreach (str_split($characters) as $char) {
        $candidate = $prefix . $char;
        $candidate_block = substr($candidate, -8);
        $candidate_hash = crypt($candidate_block, $salt);
        if ($candidate_hash === $target_block) {
            $known_key .= $char;
            echo COLOR_GREEN . ">>> Lock cracked! Found: $char (Secret so far: $known_key)" . COLOR_RESET . "\n";
            $progress = floor((strlen($known_key) / 10) * 20); // 10 steps = 20 width
            $bar = str_repeat("█", $progress) . str_repeat(" ", 20 - $progress);
            echo COLOR_CYAN . "Progress: [$bar] " . strlen($known_key) . "/10 locks opened" . COLOR_RESET . "\n\n";
            $found = true;
            sleep(1);
            break;
        }
    }
    
    if (!$found) {
        echo COLOR_YELLOW . ">>> No match found. Simulation paused at: $known_key" . COLOR_RESET . "\n";
        break;
    }
    
    $position++;
}

echo COLOR_GREEN . "=== Crypto Cracker Lab Complete! ===\nLearned secret (10 steps): $known_key" . COLOR_RESET . "\n";

?>
