<?php
// script generated by Grok, this script print key directly with no debug info
// script for tryhackme room Crypto Failures
// room link: https://tryhackme.com/room/cryptofailures

$host = "10.10.76.4";
$port = 80;
$chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_+-=[]{}|;:,.<>?';

echo "=== Welcome to Crypto Cracker Lab ===\n";

function get_cookie($ua) {
    global $host, $port;
    $socket = @stream_socket_client("tcp://$host:$port", $errno, $errstr, 5);
    if (!$socket) return null;
    
    $req = "GET / HTTP/1.1\r\nHost: $host\r\nUser-Agent: $ua\r\nAccept: */*\r\nConnection: close\r\n\r\n";
    fwrite($socket, $req);
    $resp = stream_get_contents($socket);
    fclose($socket);
    
    $start = strpos($resp, 'secure_cookie=');
    if ($start === false) return null;
    $start += 14;
    $end = strpos($resp, ';', $start);
    return $end === false ? substr($resp, $start) : substr($resp, $start, $end - $start);
}

$key = "";
$username = "guest:";
$separator = ":";

while (true) {
    $len = strlen($username . $separator . $key);
    $pad_len = ((7 - $len) % 8 + 8) % 8;
    $ua = str_repeat("A", $pad_len);
    $prefix = $username . $ua . $separator . $key;
    
    $cookie = get_cookie($ua);
    if (!$cookie) break;
    
    $cookie = urldecode($cookie);
    $block_idx = floor(strlen($prefix) / 8);
    $pos = $block_idx * 13;
    if ($pos + 13 > strlen($cookie)) break;
    
    $target = substr($cookie, $pos, 13);
    $salt = substr($target, 0, 2);
    
    $found = false;
    for ($i = 0; $i < strlen($chars); $i++) {
        $candidate = $prefix . $chars[$i];
        $block = substr($candidate, -8);
        if (crypt($block, $salt) === $target) {
            $key .= $chars[$i];
            $found = true;
            break;
        }
    }
    
    if (!$found) break;
}

echo "Final key: $key\n";
?>
