<?php
// script generated by Grok
// script for tryhackme room Crypto Failures Implementing your own military-grade encryption is usually not the best idea.
// room link: https://tryhackme.com/room/cryptofailures
// 
// Target server details
$host = "10.10.232.64";
$port = 80;

// Characters to brute-force
$characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_+-=[]{}|;:,.<>?';

// ANSI color codes
define('COLOR_RESET', "\033[0m");
define('COLOR_GREEN', "\033[32m");
define('COLOR_YELLOW', "\033[33m");
define('COLOR_CYAN', "\033[36m");
define('COLOR_WHITE', "\033[37m");

// Function to send raw HTTP request and get cookie
function get_secure_cookie($user_agent) {
    global $host, $port;
    
    $fp = fsockopen($host, $port, $errno, $errstr, 30);
    if (!$fp) {
        echo "Socket error: $errno - $errstr\n";
        return null;
    }
    
    $request = "GET / HTTP/1.1\r\n";
    $request .= "Host: $host\r\n";
    $request .= "User-Agent: $user_agent\r\n";
    $request .= "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8\r\n";
    $request .= "Connection: close\r\n";
    $request .= "\r\n";
    
    fwrite($fp, $request);
    $response = '';
    while (!feof($fp)) {
        $response .= fgets($fp, 1024);
    }
    fclose($fp);
    
    preg_match('/Set-Cookie: secure_cookie=([^;]+)/', $response, $matches);
    $cookie = isset($matches[1]) ? $matches[1] : null;
    echo COLOR_CYAN . "User-Agent: '$user_agent'" . COLOR_RESET . "\n";
    echo COLOR_WHITE . "Cookie: $cookie" . COLOR_RESET . "\n";
    return $cookie;
}

// Function to split cookie into 13-char hashes
function split_cookie($cookie) {
    if (!$cookie) return null;
    $secure_cookie = urldecode($cookie);
    $hashes = [];
    $pos = 0;
    while ($pos + 13 <= strlen($secure_cookie)) {
        $hashes[] = substr($secure_cookie, $pos, 13);
        $pos += 13;
    }
    if ($pos < strlen($secure_cookie)) {
        $hashes[] = substr($secure_cookie, $pos);
    }
    echo COLOR_WHITE . "Blocks: " . implode(", ", $hashes) . COLOR_RESET . "\n";
    return $hashes;
}

// Main logic
$known_key = "";
$position = 0;
$username = "guest:";
$separator = ":";

while (true) {
    // Calculate padding
    $length = strlen($username . $separator . $known_key);
    $ua_padding_length = ((7 - $length) % 8 + 8) % 8;
    $user_agent = str_repeat("A", $ua_padding_length);
    $prefix = $username . $user_agent . $separator . $known_key;
    
    // Get cookie
    $cookie = get_secure_cookie($user_agent);
    if (!$cookie) {
        echo "Failed to get cookie. Stopping.\n";
        break;
    }
    
    // Split cookie into hashes
    $hashes = split_cookie($cookie);
    if (!$hashes) {
        echo "Invalid cookie data. Stopping.\n";
        break;
    }
    
    // Target block
    $block_index = floor(strlen($prefix) / 8);
    if (!isset($hashes[$block_index])) {
        echo COLOR_YELLOW . "Not enough hash blocks. Key might be complete: $known_key" . COLOR_RESET . "\n";
        break;
    }
    
    $target_block = $hashes[$block_index];
    $salt = substr($target_block, 0, 2);
    echo COLOR_WHITE . "Targeting block $block_index, hash: $target_block" . COLOR_RESET . "\n";
    echo COLOR_WHITE . "Salt: $salt" . COLOR_RESET . "\n";
    echo COLOR_YELLOW . "Test block: $prefix" . COLOR_RESET . "\n";
    
    // Brute-force
    $found = false;
    foreach (str_split($characters) as $char) {
        $candidate = $prefix . $char;
        $candidate_block = substr($candidate, -8); // Last 8 bytes
        $candidate_hash = crypt($candidate_block, $salt);
        if ($candidate_hash === $target_block) {
            $known_key .= $char;
            echo COLOR_GREEN . "Found character: $char (Key so far: $known_key)" . COLOR_RESET . "\n";
            $found = true;
            break;
        }
    }
    
    if (!$found) {
        echo COLOR_YELLOW . "Couldn't find next character. Final key: $known_key" . COLOR_RESET . "\n";
        break;
    }
    
    $position++;
}

echo COLOR_GREEN . "Final key: $known_key" . COLOR_RESET . "\n";

?>
