# script generated by  Gemini and Chatgpt
# script for Tryhackme room Signed Messages https://tryhackme.com/room/lafb2026e8
# YouTube video walk through TryHackMe Signed Messages https://youtu.be/fUNkK04-R18

import hashlib
from sympy import nextprime
from Crypto.PublicKey import RSA
from Crypto.Signature import pss
from Crypto.Hash import SHA256

# --- [ CONFIGURATION ] ---
TARGET_USER = "admin"
# Ensure this is byte-perfect from the page source
TARGET_MESSAGE = "Welcome to LoveNote! Send encrypted love messages this Valentine's Day. Your communications are secured with industry-standard RSA-2048 digital signatures."

def generate_admin_key():
    print(f"[*] Generating 512-bit key for: {TARGET_USER}")
    seed_str = f"{TARGET_USER}_lovenote_2026_valentine"
    seed_bytes = seed_str.encode('utf-8')
    
    # Derive P
    sha256_p = hashlib.sha256(seed_bytes).hexdigest()
    p = nextprime(int(sha256_p, 16))
    
    # Derive Q
    sha256_q = hashlib.sha256(seed_bytes + b"pki").hexdigest()
    q = nextprime(int(sha256_q, 16))
    
    # Construct Key
    n = p * q
    e = 65537
    phi = (p - 1) * (q - 1)
    d = pow(e, -1, phi)
    
    return RSA.construct((n, e, d))

def forge_signature(key, message):
    h = SHA256.new(message.encode('utf-8'))
    
    # --- YOUR FIX: CALCULATE MAX SALT ---
    modBits = key.size_in_bits()
    
    # emLen = ceil((modBits - 1) / 8)
    emLen = (modBits - 1 + 7) // 8 
    
    # Max Salt = emLen - digestLen - 2
    maxSalt = emLen - h.digest_size - 2
    
    print(f"[*] Key Size: {modBits} bits")
    print(f"[*] EM Length: {emLen} bytes")
    print(f"[*] Calculated Max Salt: {maxSalt} bytes")
    
    if maxSalt < 0:
        raise ValueError("Key is too small even for 0 salt!")

    # Sign using the calculated max salt
    signer = pss.new(key, salt_bytes=maxSalt)
    signature = signer.sign(h)
    
    return signature.hex()

# --- [ EXECUTION ] ---
try:
    admin_key = generate_admin_key()
    signature = forge_signature(admin_key, TARGET_MESSAGE)
    
    print("\n" + "="*60)
    print(" >>> FINAL ADMIN SIGNATURE <<< ")
    print("="*60)
    print(signature)
    print("="*60)
    print("1. Go to Verify Page.")
    print("2. User: admin")
    print("3. Paste the signature above.")

except Exception as e:
    print(f"[!] Error: {e}")
