# script generated by chatgpt
# script for TryHackMe Room : Rabbit Store https://tryhackme.com/room/rabbitstore
# this script to root password in the room
# The script takes the provided RabbitMQ password hash (the one from the HTTP API output) and base64-decodes it.
# It then removes the first 4 bytes (the salt) and retains the remaining 32 bytes, which represent the actual SHA‑256 hash of the RabbitMQ root user's password.
# example: python3 extract_hash.py "49e6hSldH[redacted]U+YBzWF"


#!/usr/bin/env python3
import sys
import base64

def extract_sha256(rabbit_hash):
    try:
        decoded = base64.b64decode(rabbit_hash)
    except Exception as e:
        print("Error decoding base64:", e)
        sys.exit(1)
    
    if len(decoded) != 36:
        print("Unexpected decoded length: expected 36 bytes, got", len(decoded))
        sys.exit(1)
    
    salt = decoded[:4]
    sha256_hash = decoded[4:]
    return salt, sha256_hash

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <rabbitmq_password_hash>".format(sys.argv[0]))
        sys.exit(1)
    
    rabbit_hash = sys.argv[1]
    salt, sha256_hash = extract_sha256(rabbit_hash)
    print("Salt (hex):", salt.hex())
    print("SHA-256 hash (hex):", sha256_hash.hex())
