#script generated by Gemini
# script for TryHackMe room Length Extension Attacks https://tryhackme.com/room/lengthextensionattacks
# YouTube video walk through: https://youtu.be/KWZ96xaRpDY

import hashpumpy
import requests
import urllib.parse

# 1. Configuration
current_hash = "bfe0fa5c36531773c73dcc8d2a931301f69cf9add05a1f35dcfa2d48b44c37f0"
original_data = "username=user;role=0"
append_data = ";role=1"
key_length = 8

# 2. Calculate the new hash and the padded data
# hashpumpy.hashpump(hexdigest, original_data, data_to_add, key_length)
new_hash, new_data = hashpumpy.hashpump(current_hash, original_data, append_data, key_length)

# 3. Print the results (URL encoded for the cookie)
print(f"New Hash (hsh): {new_hash}")
print(f"New Data (auth): {urllib.parse.quote(new_data)}")
